%{
Date Created: 2/22/2025
Description:
This script generates a series of group-level plots from precomputed 
LFP, spectrogram, and PSD results.

It assumes that the following variables have already been created in the
workspace (e.g., via `aggBehavior.mlx` and related preprocessing 
scripts):

    Core behavioral/metadata:
        - behav_table: master table of sessions/trials.
        - pl_full_cri, pl_zero_cri: logical masks for passive listening
        full-volume vs zero-volume trials.
        - gonogo_full_cri, gonogo_zero_cri: masks for go/no-go full vs
        zero trials.
        - all_full_cri, all_zero_cri: masks combining advanced sessions 
        and passive listening across tasks.
        - all_full_data, all_zero_data: preloaded LFP trial data 
        structures for all_full and all_zero conditions (used by PSD 
        code).
        - time_segments: cell array of index ranges used for PSD time
        windows (baseline, early, late).

    Spectrogram (time–frequency) results:
        - fft_all_conds: struct containing baseline-normalized 
        spectrogram arrays for each condition and channel.
        - fft_time_vec: time vector for spectrograms (in seconds).
        - fft_freqs: frequency vector for spectrograms (in Hz).
        - an_names_all_conds: matching animal IDs per condition/channel.

    PSD results:
        - pxx_result: struct of PSD estimates per condition, channel, 
        and time segment (as generated by runPSD).
        - pxx_freq: frequency vector for PSD (in Hz).

    Permutation-based significance results:
        - Cluster-based permutation outputs for spectrograms and PSDs 
        have been saved to disk under `save_root` and can be accessed 
        by:
            getStatResults      (for spectrograms)
            getStatResults_psd  (for PSD segments)

The script performs the following steps:
    1. Plots group-averaged spectrograms for all_full and all_zero, and
    their difference (all_full - all_zero).
    2. Uses permutation-based cluster statistics to generate difference
    spectrograms with significance masks applied.
    3. Uses permutation results to identify significant PSD frequencies 
    and saves them to disk.
    4. Plots group-level PSD curves (baseline-normalized) for all_full 
    vs all_zero, and optionally for lick vs no-lick across intensity
    quantiles.
%}

%% Set figure save directory
% Directory used as the root location for saving most figures.
save_dir = ['..\Figure Outputs\']; 

%% Plot group spectrograms (FFT) for all_full vs all_zero
% Plot group-averaged spectrograms for merged full vs zero conditions using
% the spectrogram outputs stored in `fft_all_conds`. Each subplot shows the
% mean time–frequency response across animals for a particular channel.
plot_fft = true;     

if plot_fft
         plotGroupSpectrogam(fft_all_conds,'all_full','all_zero',...
         fft_time_vec,fft_freqs,save_dir,[0 100],[-0.75 0.75])
end   

%% Plot group difference spectrograms (all_full - all_zero)
% Plot the group-average difference spectrogram (all_full minus all_zero)
% across animals and channels, using `plotGroupDifferenceSpectrogram`. This
% highlights condition differences in the time–frequency domain prior to
% applying permutation-based significance masking.
plotGroupDifferenceSpectrogram(fft_all_conds,'all_full','all_zero',an_names_all_conds,...
         fft_time_vec,fft_freqs,save_dir,[],[-0.5 0.5])

%% Plot group difference spectrograms with significance (all_full - all_zero)
% Use permutation-based cluster statistics to reconstruct a difference
% spectrogram that retains only time–frequency points belonging to
% clusters that survive significance testing. Each channel is plotted
% separately with significant regions overlaid.
channels = fieldnames(fft_all_conds.all_full);

% Root directory for permutation test outputs generated by
% runSpatialTemporalPermOnSpectrogram.mlx.
save_root = '..\Analyis Outputs\Permutation Tests\';

all_cond_pairs = {{'all_full','all_zero'}} ;

for ipair = 1:length(all_cond_pairs)
        curr_pair = all_cond_pairs{ipair}; 
    
        curr_cond1 = curr_pair{1}; 
        curr_cond2 = curr_pair{2}; 
        
        curr_data_type = [curr_cond1 '_minus_' curr_cond2] ; 

        for ich = 1:length(channels)
            curr_ch = channels{ich}; 

            % Load and reconstruct the statistically significa  nt difference
            % map for this channel and condition contrast.
            curr_data_w_sig = getStatResults(save_root,curr_ch,curr_data_type) ;

            % Plot difference spectrogram with significance applied.
            plotWithSigGroupDifferenceSpectrogram(curr_data_w_sig,fft_time_vec,...
                fft_freqs,curr_ch,curr_data_type,[0 100],[-0.5 0.5])

        end 
end 

%% Plot individual group spectrograms with significance passive Listening vs Go/No-Go
% For each task separately (Passive Listening and Go/No-go), we:
%   1. Compute and plot the group-averaged difference spectrogram
%   (full-volume minus zero-volume; e.g., pl_full − pl_zero).
%   2. Load permutation-based cluster statistics for the corresponding
%   contrast (e.g., pl_full_minus_pl_zero).
%   3. Plot a significance-masked difference spectrogram in which only
%   time–frequency points belonging to significant clusters are retained.
%
% This code is used to recreate S1

% Root directory for permutation test outputs generated by
% runSpatialTemporalPermOnSpectrogram.mlx.
save_root = '..\Analyis Outputs\Permutation Tests\';

% passive listening
plotGroupDifferenceSpectrogram(fft_all_conds,'pl_full','pl_zero',...
    an_names_all_conds,fft_time_vec,fft_freqs,save_dir,[],[-0.5 0.5])

pl_sig = getStatResults(save_root,'Frontal_Association_Region',...
    'pl_full_minus_pl_zero');
plotWithSigGroupDifferenceSpectrogram(pl_sig,fft_time_vec,fft_freqs,...
    'Frontal_Association_Region','pl_full_minus_pl_zero',[0 100],[-0.5 0.5])

% go/no-go
plotGroupDifferenceSpectrogram(fft_all_conds,'gonogo_full','gonogo_zero',...
    an_names_all_conds,fft_time_vec,fft_freqs,save_dir,[],[-0.5 0.5])

gng_sig = getStatResults(save_root,'Frontal_Association_Region',...
    'gonogo_full_minus_gonogo_zero');
plotWithSigGroupDifferenceSpectrogram(gng_sig,fft_time_vec,fft_freqs,...
    'Frontal_Association_Region','gonogo_full_minus_gonogo_zero',[0 100],[-0.5 0.5])

%% Compute PSD significance summaries for all_full vs all_zero
% Use permutation-based cluster statistics for spectrogram data to
% determine which frequencies show significant differences between
% conditions in specific post-stimulus time segments. The resulting
% significant frequency bands are saved in `psd_sig.mat` for later
% reference or reporting.
channels = fieldnames(all_full_data); 
save_root = '...\Analysis Outputs\' ;

all_cond_pairs = {{'all_full','all_zero'}} ;

all_cond_sig = [] ;
for ipair = 1:length(all_cond_pairs)
        curr_pair = all_cond_pairs{ipair}; 
    
        curr_cond1 = curr_pair{1}; 
        curr_cond2 = curr_pair{2}; 
        
        curr_data_type = [curr_cond1 '_minus_' curr_cond2] ; 

        for ich = 1:length(channels)
            curr_ch = channels{ich};


            % For each channel and time segment, recover the set of 
            % frequencies that show any significant deviation between 
            % conditions. 
            curr_sig_freqs = getStatResults_psd(time_segments(2:3),fft_time_vec,fft_freqs,...
                save_root,curr_ch,curr_data_type) ;
            
            all_cond_sig.(curr_data_type).(curr_ch) = curr_sig_freqs;
        end 
end

% Save PSD significance structure for later use or for reporting the
% frequency bands that exhibit significant condition differences.
save(fullfile('...\Analysis Outputs\PSD Analysis\','psd_sig.mat'),"all_cond_sig");

%% Plot group PSD for all_full vs all_zero and for lick vs no-lick
% Generate group-level PSD plots (baseline-normalized) for full vs zero
% conditions
plot_psd = true ; 

% Names of the time segments used in PSD (must match `time_segments`).
seg_names = {'baseline (-500-0ms)','0-250ms','250ms-1000ms'}; 

% Condition pairs to compare for auditory full vs zero.
cond_pairs = {{'all_full','all_zero'}} ; 

% Colors for the segments (0-250ms and 250-1000ms).
colors = {'r','b'} ;

if plot_psd 
    % Plot PSD for full vs zero conditions and collect baseline-normalized
    % PSD arrays for potential additional analyses.
    [aud_pxx_result_for_sig,bl_aud_pxx_result] = plotPSD(pxx_result,pxx_freq,cond_pairs,seg_names,colors,[0 100] ,[-2 5],'');
end 

%% Functions: group difference spectrograms (cond1 - cond2)
function plotGroupDifferenceSpectrogram(data_all_conds,cond1_name,cond2_name,animals_all_conds,time_vec,freqs,save_dir,y_limits,color_limits)
        
        % Extract data and animal names for the two conditions.
        cond1_data = data_all_conds.(cond1_name); 
        cond2_data = data_all_conds.(cond2_name);

        cond1_animals = animals_all_conds.(cond1_name); 
        cond2_animals = animals_all_conds.(cond2_name);

        new_ch_locations = fieldnames(cond1_data) ;

        % Loop over channels and compute the animal-wise difference between
        % conditions, then average across animals to obtain a group-level
        % difference spectrogram.
        for ic = 1:length(new_ch_locations)
            
            this_ch = new_ch_locations{ic}; 

            this_ch_cond1_data = cond1_data.(this_ch) ; 
            this_ch_cond2_data = cond2_data.(this_ch) ; 
        
            this_ch_cond1_animals = cond1_animals.(this_ch) ;
            this_ch_cond2_animals = cond2_animals.(this_ch) ;
    
            % Ensure we only compare animals present in both conditions.
            if length(this_ch_cond1_animals) ~= length(this_ch_cond2_animals)
               common_animals = intersect(this_ch_cond1_animals,this_ch_cond2_animals) ; 
               
               this_ch_cond1_animals = this_ch_cond1_animals(ismember(this_ch_cond1_animals,common_animals));
            end 

            if isempty(this_ch_cond1_animals)
                continue 
            end 

            % Compute cond1 − cond2 spectrogram per animal.
            for in = 1:length(this_ch_cond1_animals)
    
                this_an = this_ch_cond1_animals{in};
                this_an_cond1_data = this_ch_cond1_data(:,:,in);
                this_an_cond2_data = this_ch_cond2_data(:,:,in);

                all_an_minus_data(:,:,in) = this_an_cond1_data - this_an_cond2_data ; 
            
            end 
            
            try
            group_minus_data = nanmean(all_an_minus_data,3) ; 
            catch   
                keyboard
            end

            % Plot the group-level difference spectrogram.
            figure; 

            colormap jet 
            imagesc(time_vec,freqs,squeeze(group_minus_data))
            ax = gca;
            ax.YDir= 'normal';
            a = colorbar ; 

            if ~isempty(color_limits)
                clim(color_limits)
            end 

            ylabel('Freqeuncy (Hz)') 
            xlabel('Time (sec)') 
            title(strcat(this_ch,'_',cond1_name,'_minus_',cond2_name),'Interpreter','none')
            xline([0 0],'k') 
    
            if ~isempty(y_limits)
                ylim(y_limits)
            end 
            xlim([-1 1])
            h = colorbar; 
            title(h,'Log(mV^2)')
            legend(['n = ' int2str(size(all_an_minus_data,3))])

        end 
        

end

%% Functions: group spectrograms for each condition
function plotGroupSpectrogam(data_all_conds,cond1_name,cond2_name,time_vec,freqs,save_dir,y_limits,color_limits)
    
    % Extract spectrogram data for the two conditions, and for each channel
    % plot the average spectrogram for cond1 and cond2 side-by-side.
    cond1_data = data_all_conds.(cond1_name) ; 
    cond2_data = data_all_conds.(cond2_name);

    new_ch_locations = fieldnames(cond1_data) ; 

    % Loop over channels and plot condition-wise average spectrograms.
    for ic = 1:length(new_ch_locations)
        f = figure; 
    
        this_ch = new_ch_locations{ic} ; 

        for icond = 1:2 
            eval(['curr_cond_data =cond' num2str(icond) '_data']) 
            eval(['curr_cond_name =cond' num2str(icond) '_name']) 
            this_ch_cond_data = curr_cond_data.(this_ch) ; 
            this_ch_cond_avg = nanmean(this_ch_cond_data,3) ; 

            subplot(1,2,icond)
            colormap jet 
            imagesc(time_vec,freqs,squeeze(this_ch_cond_avg))
            ax = gca;
            ax.YDir= 'normal';
            a = colorbar ; 

            if ~isempty(color_limits)
             clim(color_limits)
            end 

            ylabel('Freqeuncy (Hz)') 
            xlabel('Time (sec)') 
            title(strcat(this_ch,'_',curr_cond_name,'_'),'Interpreter','none')
            xline([0 0],'k') 
    
            if ~isempty(y_limits)
                ylim(y_limits)
            end 
            xlim([-1 1])
            h = colorbar; 
            title(h,'Log(mV^2)')
            legend(['n = ' int2str(size(this_ch_cond_data,3))])
       end 
  
        fontsize(f, 18, "points") 

    end 
end

%% Functions: group PSD plotting and baseline normalization
function [out_result,bl_result] = plotPSD(pxx_result,pxx_freq,cond_pairs,seg_names,colors,x_limits,y_limits,description)
    % Plot group-level PSD curves for condition pairs across time segments.
    % Segment 1 is treated as baseline, and later segments are normalized
    % by subtracting the log power of the baseline PSD.
    %
    % Outputs:
    %   out_result.(cond).(channel){seg} : baseline-normalized PSD for each
    %       non-baseline segment (one entry per time segment).
    %   bl_result.(cond).(channel)       : baseline PSD (in dB).

    all_channels = fieldnames(pxx_result.(cond_pairs{1}{1}));
    for ic = 1:length(all_channels)
         curr_ch = all_channels{ic} ; 

             for ipair = 1:length(cond_pairs)
             curr_pair = cond_pairs{ipair}; 
             
            f=figure;
             for icond = 1:length(curr_pair)
                 curr_cond = curr_pair{icond} ; 
    
                subplot(2,1,icond)
                hold on 

                % Segment 1 is baseline; subtract its log power from
                % later segments.
                baseline_seg = pxx_result.(curr_cond).(curr_ch){1}; 
                for iseg = 2:length(seg_names)
       
                    curr_data = pxx_result.(curr_cond).(curr_ch){iseg} ; 
                    curr_data = pow2db(curr_data) - pow2db(baseline_seg); 
                    
                    getse = @(x) std(x,0,2)/sqrt(size(x,2));

                    shadedErrorBar(pxx_freq,nanmean(curr_data,2),getse(curr_data),...
                        'lineProps',colors{iseg-1})

                    out_result.(curr_cond).(curr_ch){iseg-1} = curr_data ;
                    
                end 

                bl_result.(curr_cond).(curr_ch) = pow2db(baseline_seg); 
                
                legend(seg_names(2:3))
                xlim(x_limits)
                if ~isempty(y_limits)
                ylim(y_limits)
                end 
  
                title([curr_ch ' ' curr_cond ' ' ['n=' int2str(size(curr_data,2))] ' ' description],'Interpreter','none')
            
                ylabel('PSD (db/Hz)')
                xlabel('Frequency (Hz)')
                fontsize(f, 18, "points")

                yline([0 0],'LineStyle','--','Color','k' )
             end 
    
             
             end 
        end
         
    
end

%% Functions: cluster-size filtering for permutation tests
function [good_pos_ids,good_neg_ids] = checkClusterSize(input_data)
    % Filter positive and negative clusters based on both p-value (< 0.05)
    % and relative size (greater than a cutoff fraction of the total
    % time–frequency grid).
    cutoff = 0.01;

    pos_clust = find(input_data.clust_info.pos_clust_pval < 0.05);
    
    good_pos_ids = []; 
    for iid = 1:length(pos_clust)
        curr_id = pos_clust(iid); 

        curr_id_size = sum(input_data.clust_info.pos_clust_ids==curr_id,'all'); 

        if curr_id_size > numel(input_data.clust_info.pos_clust_ids)*cutoff
            good_pos_ids = [good_pos_ids curr_id]; 
        end
      
    end 

    neg_clust = find(input_data.clust_info.neg_clust_pval < 0.05);
    
    good_neg_ids = []; 
    for iid = 1:length(neg_clust)
        curr_id = neg_clust(iid); 

        curr_id_size = sum(input_data.clust_info.neg_clust_ids==curr_id,'all'); 

        if curr_id_size > numel(input_data.clust_info.neg_clust_ids)*cutoff
            good_neg_ids = [good_neg_ids curr_id]; 
        end
      
    end 
    
end

%% Functions: recover significant freq bands for PSD from permutation results
function all_seg_sig = getStatResults_psd(segs,fft_time,fft_freqs,stat_dir,curr_ch_name,curr_cond_name) 

    num_permutation = 5000  ; 

    % Load permutation-based cluster statistics for the given channel and
    % condition contrast.
    input_data = load(fullfile(stat_dir,curr_cond_name,[ curr_ch_name '_permutation_stat_cluster_sumt_rand_005_',num2str(num_permutation),'_perm_' curr_cond_name '.mat']));

    curr_data = squeeze(nanmean(input_data.curr_ch_data,3));
    
    data_matrix = zeros(size(curr_data));

    % Identify cluster IDs that pass p-value and size thresholds.
    [pos_clust,neg_clust] = checkClusterSize(input_data); 
    
    % Fill positive clusters into data_matrix.
    for clust = 1:length(pos_clust)
        for time = 1:size(data_matrix,2)
            [sig_grid_voxels, col] = find(input_data.clust_info.pos_clust_ids(:,time) == pos_clust(clust));
            data_matrix(sig_grid_voxels,time) = curr_data(sig_grid_voxels,time);

        end
    end
    
    % Fill negative clusters into data_matrix.
    for clust = 1:length(neg_clust)
        for time = 1:size(data_matrix,2)
            [sig_grid_voxels, col] = find(input_data.clust_info.neg_clust_ids(:,time) == neg_clust(clust));
            data_matrix(sig_grid_voxels,time) = curr_data(sig_grid_voxels,time);
        end
    end

    % For each requested time segment, identify frequencies that show any
    % significant deviation and return their corresponding frequency 
    % values.
    for iseg = 1:length(segs)
        curr_seg_time_pts = segs{iseg} -1375; 

        start_time = curr_seg_time_pts(1) ./ 1000; 
        end_time = curr_seg_time_pts(end) ./ 1000; 

        sel_time_pts = fft_time < end_time & fft_time > start_time ; 


        curr_sig_freq = find(any(data_matrix(:,sel_time_pts) ~= 0,2)) ;

        
        all_seg_sig{iseg} = fft_freqs(curr_sig_freq); 
    end 
 
end

%% Functions: reconstruct significant difference maps from permutation results
function data_matrix = getStatResults(stat_dir,curr_ch_name,curr_cond_name) 

    num_permutation = 5000  ; 
     
    % Load permutation-based cluster statistics for the given channel and
    % condition contrast.
    input_data = load(fullfile(stat_dir,curr_cond_name,[ curr_ch_name '_permutation_stat_cluster_sumt_rand_005_',num2str(num_permutation),'_perm_' curr_cond_name '.mat']));

    curr_data = squeeze(nanmean(input_data.curr_ch_data,3));
    
    data_matrix = zeros(size(curr_data));

    % Identify cluster IDs that pass p-value and size thresholds.
    [pos_clust,neg_clust] = checkClusterSize(input_data); 
    
    % Fill positive clusters into data_matrix.
    for clust = 1:length(pos_clust)
        for time = 1:size(data_matrix,2)
            [sig_grid_voxels, col] = find(input_data.clust_info.pos_clust_ids(:,time) == pos_clust(clust));
            data_matrix(sig_grid_voxels,time) = curr_data(sig_grid_voxels,time);
        end
    end
    
    % Fill negative clusters into data_matrix.
    for clust = 1:length(neg_clust)
        for time = 1:size(data_matrix,2)
            [sig_grid_voxels, col] = find(input_data.clust_info.neg_clust_ids(:,time) == neg_clust(clust));
            data_matrix(sig_grid_voxels,time) = curr_data(sig_grid_voxels,time);
        end
    end
end

%% Functions: plot difference spectrogram with significance mask applied
function plotWithSigGroupDifferenceSpectrogram(diff_data,time_vec,freqs,channel_name,curr_data_type,y_limits,color_limits)
        
    % Plot a difference spectrogram with significant time–frequency points
    % retained (diff_data) and non-significant points zeroed by prior 
    % steps.
    figure; 

    colormap jet 
    imagesc(time_vec,freqs,diff_data)
    ax = gca;
    ax.YDir= 'normal';
    a = colorbar ; 

    if ~isempty(color_limits)
        clim(color_limits)
    end 

    ylabel('Freqeuncy (Hz)') 
    xlabel('Time (sec)') 
    title(strcat(channel_name,'_',curr_data_type),'Interpreter','none')
    xline([0 0],'k') 

    if ~isempty(y_limits)
        ylim(y_limits)
    end 
    xlim([-1 1])
    h = colorbar; 
    title(h,'Log(mV^2)')
end 